/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { AboutMeInterface, HeaderStickyInterface, PortfolioInterface, SkillsInterface, } from "./components/res/interface/common.interface";
export namespace Components {
    interface CntFlexyViewSaqhanPromoAboutMe {
        "payload": AboutMeInterface;
    }
    interface CntFlexyViewSaqhanPromoAboutMeWrapper1_01 {
        "payload": AboutMeInterface;
    }
    interface CntFlexyViewSaqhanPromoContactForm {
        "payload": AboutMeInterface;
    }
    interface CntFlexyViewSaqhanPromoContactFormWrapper1_01 {
        "payload": AboutMeInterface;
    }
    interface CntFlexyViewSaqhanPromoFooter {
        "categories": HeaderStickyInterface;
    }
    interface CntFlexyViewSaqhanPromoFooterWrapper {
        "categories": HeaderStickyInterface;
    }
    interface CntFlexyViewSaqhanPromoHeader {
        /**
          * data for stickuTop€€
         */
        "categories": HeaderStickyInterface;
    }
    interface CntFlexyViewSaqhanPromoHeaderWrapper1_01 {
        /**
          * data for stickuTop€€
         */
        "categories": HeaderStickyInterface;
    }
    interface CntFlexyViewSaqhanPromoPortfolio {
        "payload": PortfolioInterface;
    }
    interface CntFlexyViewSaqhanPromoPortfolioWrapper1_01 {
        "payload": PortfolioInterface;
    }
    interface CntFlexyViewSaqhanPromoSkils {
        "payload": SkillsInterface[];
    }
    interface CntFlexyViewSaqhanPromoSkilsCard {
        /**
          * data for cards
         */
        "skills": SkillsInterface;
    }
    interface CntFlexyViewSaqhanPromoSkilsWrapper1_01 {
        "payload": SkillsInterface[];
    }
    interface CntFlexyViewSaqhanPromoStickyTop {
        /**
          * data for stickuTop
         */
        "navItems": any;
        /**
          * data for stickuTop
         */
        "socialLinks": any;
    }
    interface MyComponent {
    }
}
declare global {
    interface HTMLCntFlexyViewSaqhanPromoAboutMeElement extends Components.CntFlexyViewSaqhanPromoAboutMe, HTMLStencilElement {
    }
    var HTMLCntFlexyViewSaqhanPromoAboutMeElement: {
        prototype: HTMLCntFlexyViewSaqhanPromoAboutMeElement;
        new (): HTMLCntFlexyViewSaqhanPromoAboutMeElement;
    };
    interface HTMLCntFlexyViewSaqhanPromoAboutMeWrapper1_01Element extends Components.CntFlexyViewSaqhanPromoAboutMeWrapper1_01, HTMLStencilElement {
    }
    var HTMLCntFlexyViewSaqhanPromoAboutMeWrapper1_01Element: {
        prototype: HTMLCntFlexyViewSaqhanPromoAboutMeWrapper1_01Element;
        new (): HTMLCntFlexyViewSaqhanPromoAboutMeWrapper1_01Element;
    };
    interface HTMLCntFlexyViewSaqhanPromoContactFormElement extends Components.CntFlexyViewSaqhanPromoContactForm, HTMLStencilElement {
    }
    var HTMLCntFlexyViewSaqhanPromoContactFormElement: {
        prototype: HTMLCntFlexyViewSaqhanPromoContactFormElement;
        new (): HTMLCntFlexyViewSaqhanPromoContactFormElement;
    };
    interface HTMLCntFlexyViewSaqhanPromoContactFormWrapper1_01Element extends Components.CntFlexyViewSaqhanPromoContactFormWrapper1_01, HTMLStencilElement {
    }
    var HTMLCntFlexyViewSaqhanPromoContactFormWrapper1_01Element: {
        prototype: HTMLCntFlexyViewSaqhanPromoContactFormWrapper1_01Element;
        new (): HTMLCntFlexyViewSaqhanPromoContactFormWrapper1_01Element;
    };
    interface HTMLCntFlexyViewSaqhanPromoFooterElement extends Components.CntFlexyViewSaqhanPromoFooter, HTMLStencilElement {
    }
    var HTMLCntFlexyViewSaqhanPromoFooterElement: {
        prototype: HTMLCntFlexyViewSaqhanPromoFooterElement;
        new (): HTMLCntFlexyViewSaqhanPromoFooterElement;
    };
    interface HTMLCntFlexyViewSaqhanPromoFooterWrapperElement extends Components.CntFlexyViewSaqhanPromoFooterWrapper, HTMLStencilElement {
    }
    var HTMLCntFlexyViewSaqhanPromoFooterWrapperElement: {
        prototype: HTMLCntFlexyViewSaqhanPromoFooterWrapperElement;
        new (): HTMLCntFlexyViewSaqhanPromoFooterWrapperElement;
    };
    interface HTMLCntFlexyViewSaqhanPromoHeaderElement extends Components.CntFlexyViewSaqhanPromoHeader, HTMLStencilElement {
    }
    var HTMLCntFlexyViewSaqhanPromoHeaderElement: {
        prototype: HTMLCntFlexyViewSaqhanPromoHeaderElement;
        new (): HTMLCntFlexyViewSaqhanPromoHeaderElement;
    };
    interface HTMLCntFlexyViewSaqhanPromoHeaderWrapper1_01Element extends Components.CntFlexyViewSaqhanPromoHeaderWrapper1_01, HTMLStencilElement {
    }
    var HTMLCntFlexyViewSaqhanPromoHeaderWrapper1_01Element: {
        prototype: HTMLCntFlexyViewSaqhanPromoHeaderWrapper1_01Element;
        new (): HTMLCntFlexyViewSaqhanPromoHeaderWrapper1_01Element;
    };
    interface HTMLCntFlexyViewSaqhanPromoPortfolioElement extends Components.CntFlexyViewSaqhanPromoPortfolio, HTMLStencilElement {
    }
    var HTMLCntFlexyViewSaqhanPromoPortfolioElement: {
        prototype: HTMLCntFlexyViewSaqhanPromoPortfolioElement;
        new (): HTMLCntFlexyViewSaqhanPromoPortfolioElement;
    };
    interface HTMLCntFlexyViewSaqhanPromoPortfolioWrapper1_01Element extends Components.CntFlexyViewSaqhanPromoPortfolioWrapper1_01, HTMLStencilElement {
    }
    var HTMLCntFlexyViewSaqhanPromoPortfolioWrapper1_01Element: {
        prototype: HTMLCntFlexyViewSaqhanPromoPortfolioWrapper1_01Element;
        new (): HTMLCntFlexyViewSaqhanPromoPortfolioWrapper1_01Element;
    };
    interface HTMLCntFlexyViewSaqhanPromoSkilsElement extends Components.CntFlexyViewSaqhanPromoSkils, HTMLStencilElement {
    }
    var HTMLCntFlexyViewSaqhanPromoSkilsElement: {
        prototype: HTMLCntFlexyViewSaqhanPromoSkilsElement;
        new (): HTMLCntFlexyViewSaqhanPromoSkilsElement;
    };
    interface HTMLCntFlexyViewSaqhanPromoSkilsCardElement extends Components.CntFlexyViewSaqhanPromoSkilsCard, HTMLStencilElement {
    }
    var HTMLCntFlexyViewSaqhanPromoSkilsCardElement: {
        prototype: HTMLCntFlexyViewSaqhanPromoSkilsCardElement;
        new (): HTMLCntFlexyViewSaqhanPromoSkilsCardElement;
    };
    interface HTMLCntFlexyViewSaqhanPromoSkilsWrapper1_01Element extends Components.CntFlexyViewSaqhanPromoSkilsWrapper1_01, HTMLStencilElement {
    }
    var HTMLCntFlexyViewSaqhanPromoSkilsWrapper1_01Element: {
        prototype: HTMLCntFlexyViewSaqhanPromoSkilsWrapper1_01Element;
        new (): HTMLCntFlexyViewSaqhanPromoSkilsWrapper1_01Element;
    };
    interface HTMLCntFlexyViewSaqhanPromoStickyTopElement extends Components.CntFlexyViewSaqhanPromoStickyTop, HTMLStencilElement {
    }
    var HTMLCntFlexyViewSaqhanPromoStickyTopElement: {
        prototype: HTMLCntFlexyViewSaqhanPromoStickyTopElement;
        new (): HTMLCntFlexyViewSaqhanPromoStickyTopElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "cnt-flexy-view-saqhan-promo-about-me": HTMLCntFlexyViewSaqhanPromoAboutMeElement;
        "cnt-flexy-view-saqhan-promo-about-me-wrapper-1_01": HTMLCntFlexyViewSaqhanPromoAboutMeWrapper1_01Element;
        "cnt-flexy-view-saqhan-promo-contact-form": HTMLCntFlexyViewSaqhanPromoContactFormElement;
        "cnt-flexy-view-saqhan-promo-contact-form-wrapper-1_01": HTMLCntFlexyViewSaqhanPromoContactFormWrapper1_01Element;
        "cnt-flexy-view-saqhan-promo-footer": HTMLCntFlexyViewSaqhanPromoFooterElement;
        "cnt-flexy-view-saqhan-promo-footer-wrapper": HTMLCntFlexyViewSaqhanPromoFooterWrapperElement;
        "cnt-flexy-view-saqhan-promo-header": HTMLCntFlexyViewSaqhanPromoHeaderElement;
        "cnt-flexy-view-saqhan-promo-header-wrapper-1_01": HTMLCntFlexyViewSaqhanPromoHeaderWrapper1_01Element;
        "cnt-flexy-view-saqhan-promo-portfolio": HTMLCntFlexyViewSaqhanPromoPortfolioElement;
        "cnt-flexy-view-saqhan-promo-portfolio-wrapper-1_01": HTMLCntFlexyViewSaqhanPromoPortfolioWrapper1_01Element;
        "cnt-flexy-view-saqhan-promo-skils": HTMLCntFlexyViewSaqhanPromoSkilsElement;
        "cnt-flexy-view-saqhan-promo-skils-card": HTMLCntFlexyViewSaqhanPromoSkilsCardElement;
        "cnt-flexy-view-saqhan-promo-skils-wrapper-1_01": HTMLCntFlexyViewSaqhanPromoSkilsWrapper1_01Element;
        "cnt-flexy-view-saqhan-promo-sticky-top": HTMLCntFlexyViewSaqhanPromoStickyTopElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface CntFlexyViewSaqhanPromoAboutMe {
        "payload"?: AboutMeInterface;
    }
    interface CntFlexyViewSaqhanPromoAboutMeWrapper1_01 {
        "payload"?: AboutMeInterface;
    }
    interface CntFlexyViewSaqhanPromoContactForm {
        "payload"?: AboutMeInterface;
    }
    interface CntFlexyViewSaqhanPromoContactFormWrapper1_01 {
        "payload"?: AboutMeInterface;
    }
    interface CntFlexyViewSaqhanPromoFooter {
        "categories"?: HeaderStickyInterface;
    }
    interface CntFlexyViewSaqhanPromoFooterWrapper {
        "categories"?: HeaderStickyInterface;
    }
    interface CntFlexyViewSaqhanPromoHeader {
        /**
          * data for stickuTop€€
         */
        "categories"?: HeaderStickyInterface;
    }
    interface CntFlexyViewSaqhanPromoHeaderWrapper1_01 {
        /**
          * data for stickuTop€€
         */
        "categories"?: HeaderStickyInterface;
    }
    interface CntFlexyViewSaqhanPromoPortfolio {
        "payload"?: PortfolioInterface;
    }
    interface CntFlexyViewSaqhanPromoPortfolioWrapper1_01 {
        "payload"?: PortfolioInterface;
    }
    interface CntFlexyViewSaqhanPromoSkils {
        "payload"?: SkillsInterface[];
    }
    interface CntFlexyViewSaqhanPromoSkilsCard {
        /**
          * data for cards
         */
        "skills"?: SkillsInterface;
    }
    interface CntFlexyViewSaqhanPromoSkilsWrapper1_01 {
        "payload"?: SkillsInterface[];
    }
    interface CntFlexyViewSaqhanPromoStickyTop {
        /**
          * data for stickuTop
         */
        "navItems"?: any;
        /**
          * data for stickuTop
         */
        "socialLinks"?: any;
    }
    interface MyComponent {
    }
    interface IntrinsicElements {
        "cnt-flexy-view-saqhan-promo-about-me": CntFlexyViewSaqhanPromoAboutMe;
        "cnt-flexy-view-saqhan-promo-about-me-wrapper-1_01": CntFlexyViewSaqhanPromoAboutMeWrapper1_01;
        "cnt-flexy-view-saqhan-promo-contact-form": CntFlexyViewSaqhanPromoContactForm;
        "cnt-flexy-view-saqhan-promo-contact-form-wrapper-1_01": CntFlexyViewSaqhanPromoContactFormWrapper1_01;
        "cnt-flexy-view-saqhan-promo-footer": CntFlexyViewSaqhanPromoFooter;
        "cnt-flexy-view-saqhan-promo-footer-wrapper": CntFlexyViewSaqhanPromoFooterWrapper;
        "cnt-flexy-view-saqhan-promo-header": CntFlexyViewSaqhanPromoHeader;
        "cnt-flexy-view-saqhan-promo-header-wrapper-1_01": CntFlexyViewSaqhanPromoHeaderWrapper1_01;
        "cnt-flexy-view-saqhan-promo-portfolio": CntFlexyViewSaqhanPromoPortfolio;
        "cnt-flexy-view-saqhan-promo-portfolio-wrapper-1_01": CntFlexyViewSaqhanPromoPortfolioWrapper1_01;
        "cnt-flexy-view-saqhan-promo-skils": CntFlexyViewSaqhanPromoSkils;
        "cnt-flexy-view-saqhan-promo-skils-card": CntFlexyViewSaqhanPromoSkilsCard;
        "cnt-flexy-view-saqhan-promo-skils-wrapper-1_01": CntFlexyViewSaqhanPromoSkilsWrapper1_01;
        "cnt-flexy-view-saqhan-promo-sticky-top": CntFlexyViewSaqhanPromoStickyTop;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cnt-flexy-view-saqhan-promo-about-me": LocalJSX.CntFlexyViewSaqhanPromoAboutMe & JSXBase.HTMLAttributes<HTMLCntFlexyViewSaqhanPromoAboutMeElement>;
            "cnt-flexy-view-saqhan-promo-about-me-wrapper-1_01": LocalJSX.CntFlexyViewSaqhanPromoAboutMeWrapper1_01 & JSXBase.HTMLAttributes<HTMLCntFlexyViewSaqhanPromoAboutMeWrapper1_01Element>;
            "cnt-flexy-view-saqhan-promo-contact-form": LocalJSX.CntFlexyViewSaqhanPromoContactForm & JSXBase.HTMLAttributes<HTMLCntFlexyViewSaqhanPromoContactFormElement>;
            "cnt-flexy-view-saqhan-promo-contact-form-wrapper-1_01": LocalJSX.CntFlexyViewSaqhanPromoContactFormWrapper1_01 & JSXBase.HTMLAttributes<HTMLCntFlexyViewSaqhanPromoContactFormWrapper1_01Element>;
            "cnt-flexy-view-saqhan-promo-footer": LocalJSX.CntFlexyViewSaqhanPromoFooter & JSXBase.HTMLAttributes<HTMLCntFlexyViewSaqhanPromoFooterElement>;
            "cnt-flexy-view-saqhan-promo-footer-wrapper": LocalJSX.CntFlexyViewSaqhanPromoFooterWrapper & JSXBase.HTMLAttributes<HTMLCntFlexyViewSaqhanPromoFooterWrapperElement>;
            "cnt-flexy-view-saqhan-promo-header": LocalJSX.CntFlexyViewSaqhanPromoHeader & JSXBase.HTMLAttributes<HTMLCntFlexyViewSaqhanPromoHeaderElement>;
            "cnt-flexy-view-saqhan-promo-header-wrapper-1_01": LocalJSX.CntFlexyViewSaqhanPromoHeaderWrapper1_01 & JSXBase.HTMLAttributes<HTMLCntFlexyViewSaqhanPromoHeaderWrapper1_01Element>;
            "cnt-flexy-view-saqhan-promo-portfolio": LocalJSX.CntFlexyViewSaqhanPromoPortfolio & JSXBase.HTMLAttributes<HTMLCntFlexyViewSaqhanPromoPortfolioElement>;
            "cnt-flexy-view-saqhan-promo-portfolio-wrapper-1_01": LocalJSX.CntFlexyViewSaqhanPromoPortfolioWrapper1_01 & JSXBase.HTMLAttributes<HTMLCntFlexyViewSaqhanPromoPortfolioWrapper1_01Element>;
            "cnt-flexy-view-saqhan-promo-skils": LocalJSX.CntFlexyViewSaqhanPromoSkils & JSXBase.HTMLAttributes<HTMLCntFlexyViewSaqhanPromoSkilsElement>;
            "cnt-flexy-view-saqhan-promo-skils-card": LocalJSX.CntFlexyViewSaqhanPromoSkilsCard & JSXBase.HTMLAttributes<HTMLCntFlexyViewSaqhanPromoSkilsCardElement>;
            "cnt-flexy-view-saqhan-promo-skils-wrapper-1_01": LocalJSX.CntFlexyViewSaqhanPromoSkilsWrapper1_01 & JSXBase.HTMLAttributes<HTMLCntFlexyViewSaqhanPromoSkilsWrapper1_01Element>;
            "cnt-flexy-view-saqhan-promo-sticky-top": LocalJSX.CntFlexyViewSaqhanPromoStickyTop & JSXBase.HTMLAttributes<HTMLCntFlexyViewSaqhanPromoStickyTopElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
